spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.248.129:3306/db_second_kill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池的名称
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 300 # 数据库连接超时时间
      connection-test-query: select 1 # 心跳测试
  rabbitmq:
    virtual-host: seckill
    host: 192.168.248.129
    port: 5672
    username: java
    password: java
    listener:
      simple:
        concurrency: 5
        max-concurrency: 15
        prefetch: 10  # 指定一个请求能处理多少个消息
  redis:
    port: 6379
    host: 192.168.248.129




mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.weiheng.secondkill.pojo  # mybatis返回的类型别名


logging:
  level:
    com.weiheng.secondkill.mapper: debug


jwt:
  header: Authorization
  token-start-with: JWT
  base64-secret: jtt7xr+66mjfkhov=1chA49dellkuqxfpm6n1eeqtahj9gh9mf
  token-validity-in-seconds: 14400000

#秒杀成功异步发送邮件的消息模型
mq:
  kill:
    success:
      mail:
        queue: seckill.kill.item.success.email.queue
        exchange: seckill.kill.item.success.email.exchange
        routing:
          key: seckill.kill.item.success.email.routing.key
    wait_pay: # 支付成功后，将队列加入待支付检查队列中
      queue: seckill.kill.item.wait_pay.order.queue
      exchange: seckill.kill.item.wait_pay.order.exchange
      routing:
        key: seckill.kill.item.wait_pay.order.routing.key
    close:
      queue: seckill.kill.item.close.order.queue
      exchange: seckill.kill.item.close.order.exchange
      routing:
        key: seckill.kill.item.close.routing.key
    limit:
      queue: seckill.kill.item.limit.queue
      exchange: seckill.kill.item.limit.exchange
      routing:
        key: seckill.kill.item.limit.routing.key

#mq.kill.limit.exchange
#mq.kill.limit.routing.key
zk:
  host: 192.168.248.129:2181
  namespace: skill